name: learning new
on:
  push:
    branches:
      - main  # Adjust this to match your branch name if different

env:
  USERNAME: Abhijeet  # Define environment variables here

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my new step
        run: |
          echo "${{ env.USERNAME }}"
      - name: my secret username
        run: |
          echo "${{ secrets.USERNAME }}"
  NewTest:
    environment : Production
    runs-on: ubuntu-latest
    steps:
      - name: print production pass
        run: |
          echo "${{ secrets.PROD_PASSWORD }}"
