name: learning new
on:
  push:
    branches:
      - main  # Adjust this to match your branch name if different

env:
  USERNAME: Abhijeet  # Define environment variables here

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my new step
        run: |
          echo "${{ env.USERNAME }}"
      
      - name: stepup
        env:
          PASSWORD: 1234
        run: |
          echo "${{ env.PASSWORD }}"

  Second-job:
    needs: my-job  # Waits for 'my-job' to complete
    runs-on: ubuntu-latest
    steps:
      - name: my second step
        run: |
          echo "${{ env.USERNAME }}"
