name: learning new
on: push
env:
      USERNAME: Abhijeet  # Define environment variables here
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my new step
        run: |
          echo "${{ env.USERNAME }}"
      - name: stepup
        env :
         PASSWORD : 1234 
        run : |
         echo "${{ env.PASSWORD }}"

  Second-job:
     needs : my-job
     runs-on: ubuntu-latest
     steps:
      - name: my second step
        run: |
          echo "${{ env.USERNAME }}"
