name: learning new
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      USERNAME: Abhijeet  # Define environment variables here

    steps:
      - name: my new step
        run: |
          echo "${{ env.USERNAME }}"
      - name: stepup
        env :
         PASSWORD : 1234 
        run : |
         echo "${{ env.PASSWORD }}"


      
